### ISSUE TITLE
v5 感想

### ISSUE THREAD

**Issue by bouzuya** [bouzuya/ergodox#14]
v5 感想
Good: TO 0 うまく機能している

- [x] トラックボール併用時に Cmd の位置が若干押しづらい気がする。 #22
- [x] L1 でも modifier がほしい #21
- [x] 入力が遅れる野が嫌なので z / の設定は消す。 #15
- [x] `が入力できない。 #16
- [x] ~が入力できない。 #17
- [x] セミコロンを放棄したほうが良さそう。 #20
- [x] Enter が押しにくい。シフトを誤爆しそうになる。 #18
- [x] Backspace の利用頻度と位置のバランスが悪い #18
- [x] とにかく Enter & Backspace の位置が悪い。 #18
- [x] 数字のゼロが遠い #1
- [x] 記号のシフトレイヤーが遠く感じる。慣れかな。→様子見
- [x] なぞのアンスコが残っている。 #19

**Comment by bouzuya** [comment]
Issue 化したので close
